import { type Category } from './types';

export const CATEGORIES: Category[] = [
  {
    id: 'quantitative-aptitude',
    name: 'Quantitative Aptitude',
    description: 'Test your ability to solve numerical problems and interpret data.',
    duration: 1, // 1 minute for demo
    questions: [
      {
        id: 'q1',
        question: 'What is 25% of 200?',
        options: ['25', '40', '50', '60'],
        answer: '50',
        explanation: '25% of 200 is (25/100) * 200 = 50.',
      },
      {
        id: 'q2',
        question: 'A car travels at a speed of 60 km/h. How far will it travel in 2.5 hours?',
        options: ['120 km', '150 km', '180 km', '100 km'],
        answer: '150 km',
        explanation: 'Distance = Speed × Time. So, 60 km/h * 2.5 h = 150 km.',
      },
       {
        id: 'q3',
        question: 'If a box contains 12 red balls and 18 blue balls, what is the ratio of red balls to blue balls?',
        options: ['2:3', '3:2', '1:2', '2:1'],
        answer: '2:3',
        explanation: 'The ratio is 12:18, which simplifies to 2:3 by dividing both numbers by 6.',
      },
      {
        id: 'q4',
        question: 'The sum of two numbers is 25 and their difference is 5. What are the numbers?',
        options: ['10 and 15', '12 and 13', '10 and 5', '20 and 5'],
        answer: '10 and 15',
        explanation: 'Let the numbers be x and y. x+y=25, x-y=5. Solving these equations gives x=15, y=10.',
      },
      {
        id: 'q5',
        question: 'A train 100m long is running at a speed of 30 km/hr. Find the time taken by it to pass a man standing near the railway line.',
        options: ['10 seconds', '12 seconds', '15 seconds', '20 seconds'],
        answer: '12 seconds',
        explanation: 'Speed in m/s = 30 * (5/18) = 25/3 m/s. Time = Distance/Speed = 100 / (25/3) = 12 seconds.',
      },
      {
        id: 'q6',
        question: 'Find the average of the first 50 natural numbers.',
        options: ['25', '25.5', '26', '50'],
        answer: '25.5',
        explanation: 'The sum of the first n natural numbers is n(n+1)/2. The sum is 50(51)/2 = 1275. The average is 1275/50 = 25.5.',
      },
      {
        id: 'q7',
        question: 'What is the value of x if 3x - 7 = 14?',
        options: ['3', '5', '7', '9'],
        answer: '7',
        explanation: '3x = 14 + 7 => 3x = 21 => x = 7.',
      },
      {
        id: 'q8',
        question: 'The area of a circle is 154 sq. cm. Find its circumference.',
        options: ['22 cm', '44 cm', '66 cm', '88 cm'],
        answer: '44 cm',
        explanation: 'Area = πr². 154 = (22/7) * r² => r² = 49 => r = 7 cm. Circumference = 2πr = 2 * (22/7) * 7 = 44 cm.',
      },
      {
        id: 'q9',
        question: 'A shopkeeper sells a product for $150 at a 20% profit. What is the cost price?',
        options: ['$120', '$125', '$130', '$135'],
        answer: '$125',
        explanation: 'Let the cost price be C. C + 0.20C = 150 => 1.2C = 150 => C = 150 / 1.2 = $125.',
      },
      {
        id: 'q10',
        question: 'What is the simple interest on $500 for 2 years at 5% per annum?',
        options: ['$25', '$50', '$75', '$100'],
        answer: '$50',
        explanation: 'Simple Interest = P * R * T / 100 = 500 * 5 * 2 / 100 = $50.',
      },
    ],
  },
  {
    id: 'logical-reasoning',
    name: 'Logical Reasoning',
    description: 'Assess your logical thinking and problem-solving skills.',
    duration: 1, // 1 minute for demo
    questions: [
      {
        id: 'l1',
        question: 'Which number should come next in the series: 1, 4, 9, 16, __?',
        options: ['20', '25', '30', '36'],
        answer: '25',
        explanation: 'The series consists of squares of consecutive integers (1^2, 2^2, 3^2, 4^2). The next is 5^2 = 25.',
      },
      {
        id: 'l2',
        question: 'Statement: All cats are animals. Mittens is a cat. Conclusion?',
        options: ['Mittens is not an animal', 'All animals are cats', 'Mittens is an animal', 'Some cats are not animals'],
        answer: 'Mittens is an animal',
        explanation: 'This is a straightforward deduction from the given premises.',
      },
      {
        id: 'l3',
        question: 'If CAT is coded as DBU, how is DOG coded?',
        options: ['EPH', 'FPI', 'EPH', 'COH'],
        answer: 'EPH',
        explanation: 'Each letter is moved one step forward in the alphabet. C->D, A->B, T->U. So, D->E, O->P, G->H.',
      },
      {
        id: 'l4',
        question: 'Find the odd one out: Lion, Tiger, Leopard, Cow.',
        options: ['Lion', 'Tiger', 'Leopard', 'Cow'],
        answer: 'Cow',
        explanation: 'Lion, Tiger, and Leopard are wild carnivorous animals, while a Cow is a domestic herbivorous animal.',
      },
      {
        id: 'l5',
        question: 'Pointing to a photograph, a man said, "I have no brother or sister but that man\'s father is my father\'s son." Whose photograph was it?',
        options: ['His own', 'His son\'s', 'His father\'s', 'His nephew\'s'],
        answer: 'His son\'s',
        explanation: '"My father\'s son" is the man himself. So, the man in the photograph\'s father is the man himself. This means the photograph is of his son.',
      },
      {
        id: 'l6',
        question: 'If A is the brother of B; B is the sister of C; and C is the father of D, how is D related to A?',
        options: ['Brother', 'Sister', 'Nephew', 'Cannot be determined'],
        answer: 'Cannot be determined',
        explanation: 'A is the uncle of D. But the gender of D is not known, so we cannot determine if D is a nephew or a niece.',
      },
      {
        id: 'l7',
        question: 'A man walks 5 km toward the south and then turns to the right. After walking 3 km he turns to the left and walks 5 km. Now in which direction is he from the starting place?',
        options: ['West', 'South', 'North-East', 'South-West'],
        answer: 'South-West',
        explanation: 'He walks South, then West, then South again. His final position is to the South and West of his starting point.',
      },
      {
        id: 'l8',
        question: 'Look at this series: 7, 10, 8, 11, 9, 12, ... What number should come next?',
        options: ['7', '10', '12', '13'],
        answer: '10',
        explanation: 'This is an alternating series. One series is 7, 8, 9, ... and the other is 10, 11, 12, ... The next number belongs to the first series.',
      },
      {
        id: 'l9',
        question: 'Statement: Some actors are singers. All the singers are dancers. What is the conclusion?',
        options: ['Some actors are dancers', 'No singer is an actor', 'All actors are dancers', 'All singers are actors'],
        answer: 'Some actors are dancers',
        explanation: 'Since some actors are singers, and all singers are dancers, it follows that those actors who are singers are also dancers.',
      },
      {
        id: 'l10',
        question: 'Find the odd one out: January, May, July, November.',
        options: ['January', 'May', 'July', 'November'],
        answer: 'November',
        explanation: 'January, May, and July have 31 days, while November has 30 days.',
      },
    ],
  },
  {
    id: 'verbal-ability',
    name: 'Verbal Ability',
    description: 'Evaluate your command of the English language and comprehension.',
    duration: 1, // 1 minute for demo
    questions: [
      {
        id: 'v1',
        question: 'Choose the word that is most nearly opposite in meaning to "transparent".',
        options: ['Clear', 'Opaque', 'Bright', 'Hazy'],
        answer: 'Opaque',
        explanation: 'Opaque is the direct antonym of transparent, meaning not able to be seen through.',
      },
      {
        id: 'v2',
        question: 'Which of the following sentences is grammatically correct?',
        options: ['They is going to the park.', 'She don\'t like ice cream.', 'He plays the guitar very well.', 'We was happy to see them.'],
        answer: 'He plays the guitar very well.',
        explanation: 'The subject "He" agrees with the verb "plays". The other sentences have subject-verb agreement errors.',
      },
      {
        id: 'v3',
        question: 'Choose the synonym for "Enormous".',
        options: ['Tiny', 'Average', 'Huge', 'Soft'],
        answer: 'Huge',
        explanation: 'Enormous means very large in size, quantity, or extent. Huge is the best synonym.',
      },
      {
        id: 'v4',
        question: 'I have been living in this city ___ ten years. (Fill in the blank)',
        options: ['since', 'for', 'from', 'at'],
        answer: 'for',
        explanation: '"For" is used to denote a period of time. "Since" is used to denote a starting point.',
      },
      {
        id: 'v5',
        question: 'Find the correctly spelled word.',
        options: ['Acomodate', 'Accommodate', 'Acommodate', 'Accomodate'],
        answer: 'Accommodate',
        explanation: 'The correct spelling has two "c"s and two "m"s.',
      },
      {
        id: 'v6',
        question: 'A person who loves books is called a ___.',
        options: ['Librarian', 'Bibliophile', 'Author', 'Bookworm'],
        answer: 'Bibliophile',
        explanation: 'A bibliophile is a person who collects or has a great love of books.',
      },
      {
        id: 'v7',
        question: 'Choose the word which can be substituted for "A place where birds are kept".',
        options: ['Aquarium', 'Aviary', 'Apiary', 'Zoo'],
        answer: 'Aviary',
        explanation: 'An aviary is a large cage, building, or enclosure for keeping birds in.',
      },
      {
        id: 'v8',
        question: 'Identify the part of speech for the word \'quickly\' in "He ran quickly".',
        options: ['Adjective', 'Verb', 'Noun', 'Adverb'],
        answer: 'Adverb',
        explanation: 'Adverbs modify verbs, adjectives, or other adverbs. Here, "quickly" modifies the verb "ran".',
      },
      {
        id: 'v9',
        question: 'What is the plural of \'cactus\'?',
        options: ['Cactuses', 'Cacti', 'Cactae', 'Both A and B'],
        answer: 'Both A and B',
        explanation: 'Both "cacti" (from Latin) and "cactuses" are accepted plural forms of cactus.',
      },
      {
        id: 'v10',
        question: 'The phrase "a piece of cake" means...',
        options: ['Something difficult', 'Something very easy', 'A dessert item', 'A small portion'],
        answer: 'Something very easy',
        explanation: 'This is an idiom meaning that a task is easy to accomplish.',
      },
    ],
  },
  {
    id: 'data-interpretation',
    name: 'Data Interpretation',
    description: 'Analyze and interpret data from charts and graphs.',
    duration: 1,
    questions: [
      {
        id: 'd1',
        question: 'Based on a chart where March sales are highest, which month had the highest sales?',
        options: ['January', 'February', 'March', 'April'],
        answer: 'March',
        explanation: 'If the bar for March is the highest on the chart, it indicates the highest sales for that month.',
      },
      {
        id: 'd2',
        question: 'If sales were 100 in January and 120 in February, what was the percentage increase?',
        options: ['10%', '15%', '20%', '25%'],
        answer: '20%',
        explanation: 'Percentage increase is calculated as ((New Value - Old Value) / Old Value) * 100. So, ((120 - 100) / 100) * 100 = 20%.',
      },
      {
        id: 'd3',
        question: 'A pie chart shows 50% for apples, 30% for bananas, and 20% for oranges. If total fruits are 200, how many are bananas?',
        options: ['30', '50', '60', '100'],
        answer: '60',
        explanation: 'Number of bananas = 30% of 200 = (30/100) * 200 = 60.',
      },
      {
        id: 'd4',
        question: 'A bar graph shows monthly rainfall. Jan: 20mm, Feb: 30mm, Mar: 40mm. What is the average rainfall for the first quarter?',
        options: ['25mm', '30mm', '35mm', '40mm'],
        answer: '30mm',
        explanation: 'Average = (Total Rainfall) / (Number of Months) = (20+30+40)/3 = 90/3 = 30mm.',
      },
      {
        id: 'd5',
        question: 'In a line graph of temperature vs. time, the peak of the line is at 2 PM. At what time was the temperature the highest?',
        options: ['12 PM', '2 PM', '4 PM', '6 PM'],
        answer: '2 PM',
        explanation: 'The peak of a line graph represents the maximum value on the y-axis, which is temperature in this case.',
      },
      {
        id: 'd6',
        question: 'A table shows students in grades A and B. Grade A: 30 boys, 20 girls. Grade B: 25 boys, 25 girls. What is the total number of students?',
        options: ['50', '75', '100', '125'],
        answer: '100',
        explanation: 'Total students = (30+20) + (25+25) = 50 + 50 = 100.',
      },
      {
        id: 'd7',
        question: 'From the table in the previous question, what is the ratio of boys in Grade A to girls in Grade B?',
        options: ['30:25', '6:5', '5:6', '1:1'],
        answer: '6:5',
        explanation: 'The ratio is 30:25. Dividing both sides by 5 gives the simplified ratio 6:5.',
      },
      {
        id: 'd8',
        question: 'A pie chart for a budget shows 40% on rent. If total monthly income is $3000, how much is spent on rent?',
        options: ['$800', '$1000', '$1200', '$1500'],
        answer: '$1200',
        explanation: 'Rent = 40% of $3000 = 0.40 * 3000 = $1200.',
      },
      {
        id: 'd9',
        question: 'A bar chart shows website traffic. Mon: 1000, Tue: 1500, Wed: 1200. What was the percentage decrease from Tue to Wed?',
        options: ['10%', '15%', '20%', '25%'],
        answer: '20%',
        explanation: 'Decrease = 1500 - 1200 = 300. Percentage Decrease = (300 / 1500) * 100 = 20%.',
      },
      {
        id: 'd10',
        question: 'Based on a sales chart where Product A sold 500 units and Product B sold 250 units, what can be concluded?',
        options: ['Product A is better', 'Product B is cheaper', 'Product A sold twice as many units as Product B', 'Product B is unpopular'],
        answer: 'Product A sold twice as many units as Product B',
        explanation: 'The data only supports the quantitative comparison of sales units. 500 is twice 250.',
      },
    ],
  },
  {
    id: 'general-knowledge',
    name: 'General Knowledge',
    description: 'Test your awareness of current events and general facts.',
    duration: 1,
    questions: [
      {
        id: 'g1',
        question: 'What is the capital of Japan?',
        options: ['Beijing', 'Seoul', 'Tokyo', 'Bangkok'],
        answer: 'Tokyo',
        explanation: 'Tokyo is the capital city of Japan.',
      },
      {
        id: 'g2',
        question: 'Who wrote the play "Romeo and Juliet"?',
        options: ['Charles Dickens', 'William Shakespeare', 'Jane Austen', 'Mark Twain'],
        answer: 'William Shakespeare',
        explanation: 'William Shakespeare is the famous playwright who wrote "Romeo and Juliet".',
      },
      {
        id: 'g3',
        question: 'Which planet is known as the Red Planet?',
        options: ['Venus', 'Mars', 'Jupiter', 'Saturn'],
        answer: 'Mars',
        explanation: 'Mars is called the Red Planet because of its reddish appearance, caused by iron oxide (rust) on its surface.',
      },
      {
        id: 'g4',
        question: 'What is the largest ocean on Earth?',
        options: ['Atlantic Ocean', 'Indian Ocean', 'Arctic Ocean', 'Pacific Ocean'],
        answer: 'Pacific Ocean',
        explanation: 'The Pacific Ocean is the largest and deepest of the world\'s five oceans.',
      },
      {
        id: 'g5',
        question: 'Who is credited with inventing the light bulb?',
        options: ['Nikola Tesla', 'Thomas Edison', 'Alexander Graham Bell', 'Benjamin Franklin'],
        answer: 'Thomas Edison',
        explanation: 'While many contributed, Thomas Edison is credited with inventing the first commercially practical incandescent light bulb.',
      },
      {
        id: 'g6',
        question: 'What is the chemical symbol for gold?',
        options: ['Ag', 'Au', 'Gd', 'Go'],
        answer: 'Au',
        explanation: 'The chemical symbol for gold is Au, from the Latin word "aurum".',
      },
      {
        id: 'g7',
        question: 'In which country are the Pyramids of Giza located?',
        options: ['Greece', 'Egypt', 'Sudan', 'Mexico'],
        answer: 'Egypt',
        explanation: 'The Great Pyramids of Giza are located on the outskirts of Cairo, Egypt.',
      },
      {
        id: 'g8',
        question: 'What is the currency of the United Kingdom?',
        options: ['Euro', 'Dollar', 'Pound Sterling', 'Yen'],
        answer: 'Pound Sterling',
        explanation: 'The official currency of the United Kingdom is the Pound Sterling (£).',
      },
      {
        id: 'g9',
        question: 'Who painted the Mona Lisa?',
        options: ['Vincent van Gogh', 'Pablo Picasso', 'Leonardo da Vinci', 'Michelangelo'],
        answer: 'Leonardo da Vinci',
        explanation: 'The Mona Lisa is a world-famous portrait painted by the Italian artist Leonardo da Vinci.',
      },
      {
        id: 'g10',
        question: 'What is the highest mountain in the world?',
        options: ['K2', 'Kangchenjunga', 'Mount Everest', 'Lhotse'],
        answer: 'Mount Everest',
        explanation: 'Mount Everest, located in the Himalayas, is the Earth\'s highest mountain above sea level.',
      },
    ],
  },
  {
    id: 'mechanical-reasoning',
    name: 'Mechanical Reasoning',
    description: 'Understand and apply mechanical concepts.',
    duration: 1,
    questions: [
      {
        id: 'm1',
        question: 'If gear A turns clockwise, which way will gear C turn if they are interlocked in a line A-B-C?',
        options: ['Clockwise', 'Counter-clockwise', 'It will not turn', 'Depends on the size'],
        answer: 'Clockwise',
        explanation: 'Gear A turns clockwise, making Gear B turn counter-clockwise. Gear C, interlocked with B, will turn clockwise.',
      },
      {
        id: 'm2',
        question: 'Which principle explains why a boat floats?',
        options: ['Gravity', 'Archimedes\' Principle', 'Bernoulli\'s Principle', 'Newton\'s First Law'],
        answer: 'Archimedes\' Principle',
        explanation: 'Archimedes\' principle states that the upward buoyant force on a body in a fluid is equal to the weight of the fluid displaced by the body.',
      },
      {
        id: 'm3',
        question: 'Which type of lever has the fulcrum between the effort and the load?',
        options: ['Class 1', 'Class 2', 'Class 3', 'Class 4'],
        answer: 'Class 1',
        explanation: 'A Class 1 lever has the fulcrum located between the effort (force) and the resistance (load). A seesaw is a classic example.',
      },
      {
        id: 'm4',
        question: 'If a force of 10N is applied to a 2kg object, what is its acceleration?',
        options: ['2 m/s²', '5 m/s²', '10 m/s²', '20 m/s²'],
        answer: '5 m/s²',
        explanation: 'According to Newton\'s Second Law, Force = Mass × Acceleration (F=ma). So, Acceleration = Force / Mass = 10N / 2kg = 5 m/s².',
      },
      {
        id: 'm5',
        question: 'What happens to the pressure in a fluid when its speed increases?',
        options: ['It increases', 'It decreases', 'It stays the same', 'It becomes zero'],
        answer: 'It decreases',
        explanation: 'This is described by Bernoulli\'s Principle, which states that for an inviscid flow, an increase in the speed of the fluid occurs simultaneously with a decrease in pressure.',
      },
      {
        id: 'm6',
        question: 'A pulley system is used to lift a heavy object. What is its primary advantage?',
        options: ['It reduces the object\'s weight', 'It multiplies the force applied', 'It increases the distance the object travels', 'It changes the direction of the force'],
        answer: 'It changes the direction of the force',
        explanation: 'A single fixed pulley primarily changes the direction of the force, making it easier to lift things. Multiple pulleys can multiply the force.',
      },
      {
        id: 'm7',
        question: 'Two gears are in mesh. If the driver gear has 20 teeth and the driven gear has 40 teeth, what is the speed ratio?',
        options: ['1:2', '2:1', '1:1', '1:4'],
        answer: '2:1',
        explanation: 'The speed ratio is the inverse of the gear ratio. The driven gear will rotate at half the speed of the driver gear.',
      },
      {
        id: 'm8',
        question: 'What is the purpose of a spring in a mechanical system?',
        options: ['To create heat', 'To store potential energy', 'To conduct electricity', 'To reduce friction'],
        answer: 'To store potential energy',
        explanation: 'Springs are elastic objects that store mechanical energy. When compressed or stretched, they store potential energy.',
      },
      {
        id: 'm9',
        question: 'Which simple machine is a screw an example of?',
        options: ['Lever', 'Pulley', 'Inclined Plane', 'Wheel and Axle'],
        answer: 'Inclined Plane',
        explanation: 'A screw is essentially an inclined plane wrapped around a cylinder.',
      },
      {
        id: 'm10',
        question: 'When you turn a standard water tap (faucet), which direction loosens it (opens the valve)?',
        options: ['Clockwise', 'Counter-clockwise', 'Pushing it in', 'Pulling it out'],
        answer: 'Counter-clockwise',
        explanation: 'The standard rule is "righty-tighty, lefty-loosey". Turning counter-clockwise unscrews the valve and allows water to flow.',
      },
    ],
  },
  {
    id: 'situational-judgement',
    name: 'Situational Judgement',
    description: 'Assess your responses to hypothetical work-related situations.',
    duration: 1,
    questions: [
      {
        id: 's1',
        question: 'You notice a colleague struggling with their workload. What is the most effective action to take?',
        options: ['Tell your manager they are not performing', 'Offer to help them with some of their tasks', 'Ignore it as it\'s not your responsibility', 'Publicly point out their struggles'],
        answer: 'Offer to help them with some of their tasks',
        explanation: 'Being a supportive team member is crucial. Offering help is a constructive and positive approach.',
      },
      {
        id: 's2',
        question: 'You disagree with your manager\'s decision on a project. What should you do?',
        options: ['Complain to your colleagues', 'Do as you are told without question', 'Schedule a private meeting to discuss your concerns and suggest alternatives', 'Go above their head to their manager'],
        answer: 'Schedule a private meeting to discuss your concerns and suggest alternatives',
        explanation: 'Professional and private communication is the best way to handle disagreements and show initiative.',
      },
      {
        id: 's3',
        question: 'You are given a tight deadline for a task you feel is impossible to meet. What do you do?',
        options: ['Work overtime and hope for the best', 'Immediately inform your manager about your concerns and discuss a realistic plan', 'Delegate the task to someone else', 'Miss the deadline and explain later'],
        answer: 'Immediately inform your manager about your concerns and discuss a realistic plan',
        explanation: 'Proactive communication is key. It allows for adjustments and manages expectations.',
      },
      {
        id: 's4',
        question: 'You discover a significant error in a report that has already been sent to a client. What is your immediate action?',
        options: ['Hope no one notices', 'Blame a junior colleague', 'Inform your manager immediately and suggest a plan to correct it', 'Contact the client directly without telling your manager'],
        answer: 'Inform your manager immediately and suggest a plan to correct it',
        explanation: 'Taking ownership and being transparent is crucial for maintaining trust and resolving the issue efficiently.',
      },
      {
        id: 's5',
        question: 'A customer is angry and complaining loudly at the front desk. How should you handle the situation?',
        options: ['Argue with the customer', 'Ignore the customer until they calm down', 'Listen patiently, empathize, and move the conversation to a private area', 'Call security immediately'],
        answer: 'Listen patiently, empathize, and move the conversation to a private area',
        explanation: 'De-escalation, empathy, and professionalism are the best ways to handle a dissatisfied customer.',
      },
      {
        id: 's6',
        question: 'You are leading a team project and two members are in constant conflict, affecting the team\'s progress. What should you do?',
        options: ['Take sides with one of them', 'Let them sort it out themselves', 'Mediate a discussion between them to find common ground', 'Remove both from the project'],
        answer: 'Mediate a discussion between them to find common ground',
        explanation: 'As a leader, your role is to facilitate teamwork and resolve conflicts that hinder progress.',
      },
      {
        id: 's7',
        question: 'You are asked to perform a task that goes against company policy. What do you do?',
        options: ['Do it to please your boss', 'Refuse without explanation', 'Politely explain that it violates company policy and ask for an alternative', 'Report your boss to HR'],
        answer: 'Politely explain that it violates company policy and ask for an alternative',
        explanation: 'It is important to uphold company policy while maintaining a professional and non-confrontational demeanor.',
      },
      {
        id: 's8',
        question: 'You overhear a colleague spreading confidential company information. What is your most appropriate action?',
        options: ['Confront them publicly', 'Join in the conversation', 'Pretend you didn\'t hear anything', 'Report the incident to your manager or HR according to company procedure'],
        answer: 'Report the incident to your manager or HR according to company procedure',
        explanation: 'Protecting confidential information is a serious responsibility. Following official channels is the correct approach.',
      },
      {
        id: 's9',
        question: 'Your manager gives you negative feedback on your performance. How do you react?',
        options: ['Get defensive and make excuses', 'Listen actively, ask for specific examples, and discuss a plan for improvement', 'Ignore the feedback', 'Blame others for your poor performance'],
        answer: 'Listen actively, ask for specific examples, and discuss a plan for improvement',
        explanation: 'Viewing feedback as an opportunity for growth and responding constructively is a sign of professionalism and maturity.',
      },
      {
        id: 's10',
        question: 'You have an idea that could improve a process, but it\'s outside your job description. What should you do?',
        options: ['Keep it to yourself', 'Implement it without telling anyone', 'Write a clear proposal and present it to your manager', 'Complain that the current process is inefficient'],
        answer: 'Write a clear proposal and present it to your manager',
        explanation: 'Showing initiative and presenting well-thought-out ideas is a valuable contribution to any organization.',
      },
    ],
  },
  {
    id: 'coding-programming',
    name: 'Coding & Programming',
    description: 'Test your knowledge of basic programming concepts.',
    duration: 1,
    questions: [
      {
        id: 'c1',
        question: 'What does the "var" keyword declare in JavaScript?',
        options: ['A constant', 'A block-scoped variable', 'A function-scoped variable', 'A global variable only'],
        answer: 'A function-scoped variable',
        explanation: 'Variables declared with `var` are scoped to the function they are in, or globally if declared outside a function.',
      },
      {
        id: 'c2',
        question: 'In Python, which data type is used to store a sequence of characters?',
        options: ['int', 'float', 'char', 'str'],
        answer: 'str',
        explanation: 'The `str` data type is used for strings in Python.',
      },
      {
        id: 'c3',
        question: 'What is a boolean?',
        options: ['A number with a decimal point', 'A type of loop', 'A data type that can be either true or false', 'A text string'],
        answer: 'A data type that can be either true or false',
        explanation: 'Booleans represent the two truth values: true and false.',
      },
      {
        id: 'c4',
        question: 'In CSS, how do you select an element with id "header"?',
        options: ['.header', '#header', 'header', '*header'],
        answer: '#header',
        explanation: 'The "#" symbol is used in CSS to select elements by their ID.',
      },
      {
        id: 'c5',
        question: 'What does HTML stand for?',
        options: ['Hyper Text Markup Language', 'High Tech Modern Language', 'Hyperlink and Text Markup Language', 'Home Tool Markup Language'],
        answer: 'Hyper Text Markup Language',
        explanation: 'HTML is the standard markup language for creating web pages.',
      },
      {
        id: 'c6',
        question: 'Which of the following is NOT a programming language?',
        options: ['HTML', 'Python', 'Java', 'C++'],
        answer: 'HTML',
        explanation: 'HTML is a markup language used for structuring content, not a programming language which contains logic and algorithms.',
      },
      {
        id: 'c7',
        question: 'What is an API?',
        options: ['A type of computer chip', 'A software application', 'Application Programming Interface', 'A programming language'],
        answer: 'Application Programming Interface',
        explanation: 'An API is a set of rules and protocols that allows different software applications to communicate with each other.',
      },
      {
        id: 'c8',
        question: 'What is the result of `2 + "2"` in JavaScript?',
        options: ['4', '"22"', '22', 'Error'],
        answer: '"22"',
        explanation: 'In JavaScript, the `+` operator concatenates a string and a number, resulting in a string.',
      },
      {
        id: 'c9',
        question: 'What is the purpose of a `for` loop?',
        options: ['To declare a variable', 'To execute a block of code repeatedly', 'To make a decision', 'To define a function'],
        answer: 'To execute a block of code repeatedly',
        explanation: 'Loops are used to repeat a block of code until a certain condition is met.',
      },
      {
        id: 'c10',
        question: 'In object-oriented programming, what is inheritance?',
        options: ['The ability of an object to take on many forms', 'A mechanism where a new class inherits properties and methods from an existing class', 'The process of hiding implementation details', 'A way to create multiple instances of an object'],
        answer: 'A mechanism where a new class inherits properties and methods from an existing class',
        explanation: 'Inheritance allows for code reuse and the creation of a hierarchy of classes.',
      },
    ],
  },
  {
    id: 'spatial-reasoning',
    name: 'Spatial Reasoning',
    description: 'Assess your ability to visualize and manipulate 2D and 3D objects.',
    duration: 1,
    questions: [
      {
        id: 'sr1',
        question: 'If a cube is unfolded, how many squares will it have?',
        options: ['4', '6', '8', '12'],
        answer: '6',
        explanation: 'A cube has 6 faces, so its unfolded net will consist of 6 squares.',
      },
      {
        id: 'sr2',
        question: 'Which 3D shape can be made by folding a single piece of paper with four connected squares in a line and one on top of the second square?',
        options: ['A pyramid', 'An open-top box', 'A triangular prism', 'A cylinder'],
        answer: 'An open-top box',
        explanation: 'This "T" shape net is a classic pattern for creating an open-top box (a cube missing one face).',
      },
      {
        id: 'sr3',
        question: 'Which of the following shapes is three-dimensional?',
        options: ['Circle', 'Square', 'Sphere', 'Triangle'],
        answer: 'Sphere',
        explanation: 'A circle, square, and triangle are 2D shapes. A sphere is a 3D object.',
      },
      {
        id: 'sr4',
        question: 'You are facing North and turn 90 degrees to your right. Which direction are you facing now?',
        options: ['South', 'East', 'West', 'North'],
        answer: 'East',
        explanation: 'Turning 90 degrees to the right from North will point you East.',
      },
      {
        id: 'sr5',
        question: 'Imagine a square paper is folded in half diagonally. What shape do you get?',
        options: ['Square', 'Rectangle', 'Triangle', 'Circle'],
        answer: 'Triangle',
        explanation: 'Folding a square along its diagonal creates two right-angled triangles.',
      },
      {
        id: 'sr6',
        question: 'How many corners (vertices) does a cube have?',
        options: ['4', '6', '8', '12'],
        answer: '8',
        explanation: 'A cube has 8 vertices where the edges meet.',
      },
      {
        id: 'sr7',
        question: 'If you stack 3 cubes on top of each other, how many faces are visible (not touching another cube or the ground)?',
        options: ['10', '12', '14', '15'],
        answer: '14',
        explanation: 'Top cube: 5 visible faces. Middle cube: 4 visible faces. Bottom cube: 5 visible faces (4 sides + top is covered, bottom touches ground). Total: 5+4+5=14, assuming it is on the ground. If floating, it would be 4 sides for bottom cube so 13.',
      },
      {
        id: 'sr8',
        question: 'Which 2D shape can be rotated about an axis to form a cylinder?',
        options: ['Circle', 'Square', 'Rectangle', 'Triangle'],
        answer: 'Rectangle',
        explanation: 'Rotating a rectangle around one of its sides will sweep out the shape of a cylinder.',
      },
      {
        id: 'sr9',
        question: 'A map shows a route from A (bottom) to B (top). If you rotate the map 180 degrees, where will point A be?',
        options: ['Top', 'Bottom', 'Left', 'Right'],
        answer: 'Top',
        explanation: 'A 180-degree rotation will flip the map upside down, so the bottom point will move to the top.',
      },
      {
        id: 'sr10',
        question: 'Which of these nets will NOT form a cube? (A net is a 2D pattern that can be folded to make a 3D shape)',
        options: ['A cross shape of 6 squares', 'A line of 6 squares', '4 squares in a line with 2 attached to one side', '3 squares in a line, with 3 more squares in a line below it.'],
        answer: 'A line of 6 squares',
        explanation: 'A line of six squares cannot be folded into a cube; it will overlap.',
      },
    ],
  },
  {
    id: 'abstract-reasoning',
    name: 'Abstract Reasoning',
    description: 'Identify patterns and relationships in abstract shapes and figures.',
    duration: 1,
    questions: [
      {
        id: 'ar1',
        question: 'A sequence shows a shape rotating 90 degrees clockwise at each step. What is the next position?',
        options: ['Rotated 45 degrees', 'Rotated 90 degrees', 'Rotated 180 degrees', 'No change'],
        answer: 'Rotated 90 degrees',
        explanation: 'The pattern is a consistent 90-degree clockwise rotation.',
      },
      {
        id: 'ar2',
        question: 'Which is the odd one out in a group of shapes: Square, Circle, Triangle, Arrow?',
        options: ['Square', 'Circle', 'Triangle', 'Arrow'],
        answer: 'Arrow',
        explanation: 'Square, Circle, and Triangle are basic geometric shapes, while an arrow indicates direction and is more complex.',
      },
      {
        id: 'ar3',
        question: 'A sequence shows a square, then a square with a dot inside, then a square with two dots. What\'s next?',
        options: ['A circle', 'A square with one dot', 'A square with three dots', 'An empty square'],
        answer: 'A square with three dots',
        explanation: 'The pattern is adding one dot inside the square at each step.',
      },
      {
        id: 'ar4',
        question: 'Find the odd one out: A group of red squares, a group of red circles, a group of red triangles, a group of blue squares.',
        options: ['Red squares', 'Red circles', 'Red triangles', 'Blue squares'],
        answer: 'Blue squares',
        explanation: 'All other groups consist of red shapes. The color is the differentiating feature.',
      },
      {
        id: 'ar5',
        question: 'Analogy: A large square is to a small square as a large circle is to a ___',
        options: ['Large square', 'Small circle', 'Small triangle', 'Large circle'],
        answer: 'Small circle',
        explanation: 'The relationship is one of size (large to small). The shape should remain the same.',
      },
      {
        id: 'ar6',
        question: 'A pattern has a black circle, then a white circle, then a black circle. What\'s next?',
        options: ['A black square', 'A white square', 'A white circle', 'A black circle'],
        answer: 'A white circle',
        explanation: 'The pattern alternates between black and white colors for the circle.',
      },
      {
        id: 'ar7',
        question: 'A line moves from the top edge of a box to the middle, then to the bottom edge. What is its next position?',
        options: ['Top edge', 'Middle', 'Bottom edge', 'Outside the box'],
        answer: 'Middle',
        explanation: 'The pattern seems to be an oscillation: top, middle, bottom, middle, top...',
      },
      {
        id: 'ar8',
        question: 'One shape is inside another. In the next step, they swap positions (inner becomes outer, outer becomes inner). What is the next step?',
        options: ['They disappear', 'They stay the same', 'They swap positions again', 'They merge'],
        answer: 'They swap positions again',
        explanation: 'The logical continuation of the pattern is to repeat the transformation.',
      },
      {
        id: 'ar9',
        question: 'In a 3x3 grid, the first row has 1, 2, 3 dots. The second row has 4, 5, 6 dots. What does the third row have?',
        options: ['1, 2, 3', '3, 2, 1', '7, 8, 9', '6, 5, 4'],
        answer: '7, 8, 9',
        explanation: 'The number of dots is increasing sequentially across the rows.',
      },
      {
        id: 'ar10',
        question: 'A shape is mirrored horizontally in step 2. What happens in step 3 if the pattern repeats?',
        options: ['It is mirrored vertically', 'It is mirrored horizontally again', 'It rotates', 'It disappears'],
        answer: 'It is mirrored horizontally again',
        explanation: 'If the pattern is a simple horizontal mirror, repeating it would flip the shape back to its original orientation.',
      },
    ],
  },
  {
    id: 'numerical-reasoning',
    name: 'Numerical Reasoning',
    description: 'Interpret and use numerical data to solve problems.',
    duration: 1,
    questions: [
      {
        id: 'nr1',
        question: 'A company\'s profit increased from $50,000 to $60,000. What is the percentage increase?',
        options: ['10%', '20%', '25%', '30%'],
        answer: '20%',
        explanation: 'Increase = $10,000. Percentage Increase = (10,000 / 50,000) * 100 = 20%.',
      },
      {
        id: 'nr2',
        question: 'If a product costs $80 and is sold with a 25% profit margin, what is the selling price?',
        options: ['$90', '$100', '$105', '$110'],
        answer: '$100',
        explanation: 'Profit = 25% of $80 = $20. Selling Price = Cost + Profit = $80 + $20 = $100.',
      },
      {
        id: 'nr3',
        question: 'A car travels 200 miles on 10 gallons of fuel. What is its fuel efficiency in miles per gallon (MPG)?',
        options: ['10 MPG', '20 MPG', '25 MPG', '30 MPG'],
        answer: '20 MPG',
        explanation: 'Fuel efficiency = Total Miles / Total Gallons = 200 / 10 = 20 MPG.',
      },
      {
        id: 'nr4',
        question: 'A survey of 100 people found 60% like coffee. How many people like coffee?',
        options: ['40', '50', '60', '70'],
        answer: '60',
        explanation: '60% of 100 is (60/100) * 100 = 60 people.',
      },
      {
        id: 'nr5',
        question: 'The price of a stock dropped from $50 to $45. What is the percentage decrease?',
        options: ['5%', '10%', '15%', '20%'],
        answer: '10%',
        explanation: 'Decrease = $5. Percentage Decrease = (5 / 50) * 100 = 10%.',
      },
      {
        id: 'nr6',
        question: 'If you work 40 hours a week at $15/hour, what is your weekly gross pay?',
        options: ['$500', '$600', '$700', '$800'],
        answer: '$600',
        explanation: 'Weekly Pay = Hours Worked × Hourly Rate = 40 × 15 = $600.',
      },
      {
        id: 'nr7',
        question: 'A table shows sales figures for 4 quarters: Q1: 1000, Q2: 1500, Q3: 1200, Q4: 1800. What are the total annual sales?',
        options: ['4500', '5000', '5500', '6000'],
        answer: '5500',
        explanation: 'Total Sales = 1000 + 1500 + 1200 + 1800 = 5500.',
      },
      {
        id: 'nr8',
        question: 'From the data in the previous question, what was the average quarterly sale?',
        options: ['1300', '1375', '1400', '1425'],
        answer: '1375',
        explanation: 'Average Sale = Total Sales / Number of Quarters = 5500 / 4 = 1375.',
      },
      {
        id: 'nr9',
        question: 'A recipe requires 2 cups of flour for 12 cookies. How much flour is needed for 30 cookies?',
        options: ['3 cups', '4 cups', '5 cups', '6 cups'],
        answer: '5 cups',
        explanation: 'Flour per cookie = 2/12 = 1/6 cups. For 30 cookies, you need 30 * (1/6) = 5 cups.',
      },
      {
        id: 'nr10',
        question: 'A phone plan costs $40/month plus $0.10 per text over 100 texts. If you sent 150 texts, what is your bill?',
        options: ['$40', '$45', '$50', '$55'],
        answer: '$45',
        explanation: 'You sent 50 texts over the limit. Extra cost = 50 * $0.10 = $5. Total bill = $40 + $5 = $45.',
      },
    ],
  },
  {
    id: 'error-checking',
    name: 'Error Checking',
    description: 'Compare information and identify errors quickly and accurately.',
    duration: 1,
    questions: [
      {
        id: 'ec1',
        question: 'Original: John Smith, 123 Main St. Copy: Jon Smith, 123 Main St. Is there an error?',
        options: ['Yes', 'No'],
        answer: 'Yes',
        explanation: 'The name "John" is misspelled as "Jon" in the copy.',
      },
      {
        id: 'ec2',
        question: 'Original: AB-45-CD-12. Copy: AB-45-CD-12. Is there an error?',
        options: ['Yes', 'No'],
        answer: 'No',
        explanation: 'The copy is identical to the original.',
      },
      {
        id: 'ec3',
        question: 'Original: REF: 89012-AZ. Copy: REF: 89012-AX. Is there an error?',
        options: ['Yes', 'No'],
        answer: 'Yes',
        explanation: 'The last letter is different (Z vs X).',
      },
      {
        id: 'ec4',
        question: 'Original: Date: 11/05/2023. Copy: Date: 11/05/2023. Is there an error?',
        options: ['Yes', 'No'],
        answer: 'No',
        explanation: 'The dates are identical.',
      },
      {
        id: 'ec5',
        question: 'Original: Amount: $1,250.50. Copy: Amount: $1,250.05. Is there an error?',
        options: ['Yes', 'No'],
        answer: 'Yes',
        explanation: 'The cents are different (50 vs 05).',
      },
      {
        id: 'ec6',
        question: 'Original: Name: Sarah O\'Connor. Copy: Name: Sarah OConnor. Is there an error?',
        options: ['Yes', 'No'],
        answer: 'Yes',
        explanation: 'The apostrophe is missing in the copy.',
      },
      {
        id: 'ec7',
        question: 'Original: ID: #44-B-987. Copy: ID: #44-B-987. Is there an error?',
        options: ['Yes', 'No'],
        answer: 'No',
        explanation: 'The IDs are identical.',
      },
      {
        id: 'ec8',
        question: 'Original: Tel: (555)-123-4567. Copy: Tel: (555) 123-4567. Is there an error?',
        options: ['Yes', 'No'],
        answer: 'Yes',
        explanation: 'There is a missing hyphen after the area code parentheses.',
      },
      {
        id: 'ec9',
        question: 'Original: email@example.com. Copy: email@exampel.com. Is there an error?',
        options: ['Yes', 'No'],
        answer: 'Yes',
        explanation: '"example" is misspelled as "exampel".',
      },
      {
        id: 'ec10',
        question: 'Original: Product Code: XYZ-001. Copy: Product Code: XY-Z-001. Is there an error?',
        options: ['Yes', 'No'],
        answer: 'Yes',
        explanation: 'An extra hyphen has been added in the copy.',
      },
    ],
  },
  {
    id: 'reading-comprehension',
    name: 'Reading Comprehension',
    description: 'Read passages and answer questions based on the text.',
    duration: 1,
    questions: [
      {
        id: 'rc1',
        question: 'After reading a passage about the importance of recycling, what is the main idea?',
        options: ['Recycling is difficult.', 'Recycling helps the environment.', 'Landfills are large.', 'Paper comes from trees.'],
        answer: 'Recycling helps the environment.',
        explanation: 'The main idea is the central point of the passage.',
      },
      {
        id: 'rc2',
        question: 'Passage: The Industrial Revolution, which began in the 18th century, was a period of major industrialization. Where did it begin?',
        options: ['USA', 'France', 'Great Britain', 'Germany'],
        answer: 'Great Britain',
        explanation: 'The passage would state that the revolution originated in Great Britain.',
      },
      {
        id: 'rc3',
        question: 'Passage: The Industrial Revolution led to the mechanization of agriculture and textile manufacturing. What were two areas that were mechanized?',
        options: ['Farming and clothing', 'Mining and transport', 'Fishing and construction', 'Education and healthcare'],
        answer: 'Farming and clothing',
        explanation: 'Agriculture relates to farming, and textile manufacturing relates to clothing.',
      },
      {
        id: 'rc4',
        question: 'Passage: It had a profound effect on the social, economic, and cultural conditions of the time. What does "profound" mean?',
        options: ['Minor', 'Negative', 'Deep and significant', 'Temporary'],
        answer: 'Deep and significant',
        explanation: '"Profound" means having a strong influence or effect.',
      },
      {
        id: 'rc5',
        question: 'If a passage argues that a new law will have negative consequences, what is the author\'s tone?',
        options: ['Neutral', 'Supportive', 'Critical', 'Humorous'],
        answer: 'Critical',
        explanation: 'Arguing for negative consequences indicates a critical or concerned tone.',
      },
      {
        id: 'rc6',
        question: 'What is the purpose of a concluding sentence in a paragraph?',
        options: ['To introduce a new idea', 'To provide an example', 'To summarize the main point', 'To ask a question'],
        answer: 'To summarize the main point',
        explanation: 'The concluding sentence typically restates or summarizes the paragraph\'s main idea.',
      },
      {
        id: 'rc7',
        question: 'What can you infer from the sentence: "Despite the rain, the team decided to play the match."',
        options: ['The team likes rain', 'Rain usually stops matches', 'The team was forced to play', 'It was not raining hard'],
        answer: 'Rain usually stops matches',
        explanation: 'The word "despite" implies that the rain was a factor that would normally prevent the match from being played.',
      },
      {
        id: 'rc8',
        question: 'A passage describes the life cycle of a butterfly. What is the likely organizational structure?',
        options: ['Compare and Contrast', 'Problem and Solution', 'Chronological Order', 'Cause and Effect'],
        answer: 'Chronological Order',
        explanation: 'A life cycle is a sequence of events, which is best described in chronological (time) order.',
      },
      {
        id: 'rc9',
        question: 'What is the difference between the main idea and supporting details?',
        options: ['There is no difference', 'The main idea is a detail', 'The main idea is the central point; supporting details provide evidence', 'Supporting details are more important'],
        answer: 'The main idea is the central point; supporting details provide evidence',
        explanation: 'Supporting details (like facts, examples, and stats) exist to back up the main idea.',
      },
      {
        id: 'rc10',
        question: 'What does "it" refer to in the sentence: "The dog wagged its tail when it saw the postman."',
        options: ['The tail', 'The postman', 'The dog', 'The sentence is unclear'],
        answer: 'The dog',
        explanation: '"It" is a pronoun that refers back to the subject of the sentence, which is the dog.',
      },
    ],
  },
  {
    id: 'basic-computer-knowledge',
    name: 'Basic Computer Knowledge',
    description: 'Test your understanding of fundamental computer concepts.',
    duration: 1,
    questions: [
      {
        id: 'bck1',
        question: 'What does CPU stand for?',
        options: ['Central Processing Unit', 'Computer Personal Unit', 'Central Power Unit', 'Core Processing Unit'],
        answer: 'Central Processing Unit',
        explanation: 'The CPU is the primary component of a computer that performs most of the processing.',
      },
      {
        id: 'bck2',
        question: 'What is RAM?',
        options: ['A type of permanent storage', 'Random Access Memory, a volatile memory', 'A computer brand', 'A software program'],
        answer: 'Random Access Memory, a volatile memory',
        explanation: 'RAM is used by the CPU to store data and instructions that are currently in use. It is volatile, meaning its contents are lost when the power is turned off.',
      },
      {
        id: 'bck3',
        question: 'Which of these is an input device?',
        options: ['Monitor', 'Keyboard', 'Printer', 'Speaker'],
        answer: 'Keyboard',
        explanation: 'Input devices are used to send data to a computer. A keyboard is used to input text and commands.',
      },
      {
        id: 'bck4',
        question: 'What does "URL" stand for?',
        options: ['Uniform Resource Locator', 'Universal Resource Link', 'Uniform Record Locator', 'Universal Record Link'],
        answer: 'Uniform Resource Locator',
        explanation: 'A URL is the address of a resource (like a web page) on the internet.',
      },
      {
        id: 'bck5',
        question: 'What is a computer virus?',
        options: ['A hardware component', 'A type of malicious software', 'A computer cleaning tool', 'A network protocol'],
        answer: 'A type of malicious software',
        explanation: 'A virus is a type of malware that, when executed, replicates itself by modifying other computer programs and inserting its own code.',
      },
      {
        id: 'bck6',
        question: 'What is the function of an Operating System (OS)?',
        options: ['To browse the internet', 'To create documents', 'To manage computer hardware and software resources', 'To play games'],
        answer: 'To manage computer hardware and software resources',
        explanation: 'The OS acts as an intermediary between the user and the computer hardware.',
      },
      {
        id: 'bck7',
        question: 'Which file extension typically indicates a picture?',
        options: ['.txt', '.mp3', '.jpg', '.docx'],
        answer: '.jpg',
        explanation: '.jpg (or .jpeg) is a common file format for digital images.',
      },
      {
        id: 'bck8',
        question: 'What is \'the cloud\' in computing?',
        options: ['A type of weather forecast software', 'A network of servers that store and manage data over the internet', 'Your computer\'s hard drive', 'A type of computer screen'],
        answer: 'A network of servers that store and manage data over the internet',
        explanation: 'Cloud computing means storing and accessing data and programs over the internet instead of your computer\'s hard drive.',
      },
      {
        id: 'bck9',
        question: 'What does Wi-Fi stand for?',
        options: ['Wireless Fidelity', 'Wireless File', 'Wired Fidelity', 'It does not stand for anything'],
        answer: 'It does not stand for anything',
        explanation: 'Despite common belief, "Wi-Fi" is a trademarked name and does not officially stand for "Wireless Fidelity".',
      },
      {
        id: 'bck10',
        question: 'What is a web browser?',
        options: ['A type of search engine', 'A software application for accessing information on the World Wide Web', 'A company that provides internet service', 'A piece of computer hardware'],
        answer: 'A software application for accessing information on the World Wide Web',
        explanation: 'Examples of web browsers include Chrome, Firefox, and Safari.',
      },
    ],
  },
    {
    id: 'financial-literacy',
    name: 'Financial Literacy',
    description: 'Assess your knowledge of personal finance concepts.',
    duration: 1,
    questions: [
      {
        id: 'fl1',
        question: 'What is compound interest?',
        options: ['Interest on the principal amount only', 'Interest calculated on the initial principal and also on the accumulated interest', 'A one-time fee', 'Interest paid in advance'],
        answer: 'Interest calculated on the initial principal and also on the accumulated interest',
        explanation: 'Compound interest is "interest on interest," leading to exponential growth.',
      },
      {
        id: 'fl2',
        question: 'What is a credit score?',
        options: ['The amount of money you have', 'A number representing a person\'s creditworthiness', 'Your annual income', 'A score in a game'],
        answer: 'A number representing a person\'s creditworthiness',
        explanation: 'Lenders use credit scores to evaluate the risk of lending money to a consumer.',
      },
      {
        id: 'fl3',
        question: 'What does it mean to diversify an investment portfolio?',
        options: ['To invest in only one stock', 'To sell all your investments', 'To spread your investments across various financial instruments and industries', 'To invest only in cash'],
        answer: 'To spread your investments across various financial instruments and industries',
        explanation: 'Diversification is a strategy to reduce risk by investing in a variety of assets.',
      },
      {
        id: 'fl4',
        question: 'What is the main difference between a stock and a bond?',
        options: ['There is no difference', 'A stock represents ownership in a company, while a bond is a loan to a company or government', 'A bond represents ownership, a stock is a loan', 'Stocks are risk-free, bonds are risky'],
        answer: 'A stock represents ownership in a company, while a bond is a loan to a company or government',
        explanation: 'Stockholders are owners, while bondholders are lenders.',
      },
      {
        id: 'fl5',
        question: 'What is inflation?',
        options: ['The rate at which money grows in a savings account', 'The rate at which the general level of prices for goods and services is rising', 'A decrease in prices', 'A government tax'],
        answer: 'The rate at which the general level of prices for goods and services is rising',
        explanation: 'Inflation reduces the purchasing power of currency over time.',
      },
      {
        id: 'fl6',
        question: 'What is a 401(k)?',
        options: ['A type of savings account', 'A tax form', 'A retirement savings plan sponsored by an employer', 'A type of government bond'],
        answer: 'A retirement savings plan sponsored by an employer',
        explanation: 'It lets workers save and invest a piece of their paycheck before taxes are taken out.',
      },
      {
        id: 'fl7',
        question: 'What is a budget?',
        options: ['A plan for how to spend your money', 'A record of your past spending', 'The amount of money you earn', 'A type of investment'],
        answer: 'A plan for how to spend your money',
        explanation: 'A budget is a financial plan for a defined period, often one month or one year.',
      },
      {
        id: 'fl8',
        question: 'What is the difference between a debit card and a credit card?',
        options: ['No difference', 'A debit card takes money directly from your bank account, a credit card is a loan', 'A credit card takes money directly from your bank account, a debit card is a loan', 'Debit cards are for online shopping only'],
        answer: 'A debit card takes money directly from your bank account, a credit card is a loan',
        explanation: 'Using a debit card is like paying with cash from your account, while a credit card involves borrowing money to be paid back later.',
      },
      {
        id: 'fl9',
        question: 'Why is it important to have an emergency fund?',
        options: ['To buy luxury items', 'To cover unexpected financial emergencies', 'To invest in the stock market', 'It is not important'],
        answer: 'To cover unexpected financial emergencies',
        explanation: 'An emergency fund helps you avoid debt when unexpected expenses arise, like a medical bill or job loss.',
      },
      {
        id: 'fl10',
        question: 'What is a mortgage?',
        options: ['A savings account for a house', 'A loan used to purchase real estate', 'A type of property tax', 'Rent paid to a landlord'],
        answer: 'A loan used to purchase real estate',
        explanation: 'A mortgage is a loan from a bank or other financial institution that helps a borrower purchase a home.',
      },
    ],
  },
  {
    id: 'critical-thinking',
    name: 'Critical Thinking',
    description: 'Analyze information objectively and make a reasoned judgment.',
    duration: 1,
    questions: [
      {
        id: 'ct1',
        question: 'A study shows a correlation between ice cream sales and crime rates. What is a likely explanation?',
        options: ['Eating ice cream causes crime', 'Crime causes people to eat ice cream', 'A third factor, like hot weather, influences both', 'The study is flawed'],
        answer: 'A third factor, like hot weather, influences both',
        explanation: 'Correlation does not imply causation. A third variable is often responsible for the observed relationship.',
      },
      {
        id: 'ct2',
        question: '"All birds can fly. A penguin is a bird. Therefore, a penguin can fly." What is wrong with this reasoning?',
        options: ['The first premise is false', 'The second premise is false', 'The conclusion is false', 'The logic is invalid'],
        answer: 'The first premise is false',
        explanation: 'The initial statement "All birds can fly" is an incorrect generalization. Not all birds can fly.',
      },
      {
        id: 'ct3',
        question: 'An advertisement claims "4 out of 5 dentists recommend this toothpaste". What information is missing to evaluate this claim?',
        options: ['The price of the toothpaste', 'How many dentists were surveyed', 'The flavor of the toothpaste', 'The color of the tube'],
        answer: 'How many dentists were surveyed',
        explanation: 'The sample size is crucial. "4 out of 5" is very different from "80 out of 100". The claim is misleading without this context.',
      },
      {
        id: 'ct4',
        question: 'If a politician says "We must either raise taxes or cut public services", what kind of logical fallacy might this be?',
        options: ['Ad Hominem', 'Straw Man', 'False Dichotomy', 'Slippery Slope'],
        answer: 'False Dichotomy',
        explanation: 'A false dichotomy or false dilemma presents two opposing options as the only two options, when in fact other possibilities exist.',
      },
      {
        id: 'ct5',
        question: 'What is an unstated assumption in the statement: "This new software will increase our company\'s productivity."',
        options: ['The software is expensive', 'Employees will know how to use the software effectively', 'The old software was bad', 'The company is not productive'],
        answer: 'Employees will know how to use the software effectively',
        explanation: 'The statement assumes that the software will be implemented and used correctly and efficiently by employees.',
      },
      {
        id: 'ct6',
        question: 'If it rains, the ground will be wet. The ground is wet. Can we conclude that it rained?',
        options: ['Yes', 'No', 'Maybe', 'Only if it is daytime'],
        answer: 'No',
        explanation: 'This is a logical fallacy known as "affirming the consequent". The ground could be wet for other reasons (e.g., sprinklers).',
      },
      {
        id: 'ct7',
        question: 'You read a news article online. What is a first step in thinking critically about it?',
        options: ['Believe everything it says', 'Share it immediately', 'Check the source and author for credibility and bias', 'Read only the headline'],
        answer: 'Check the source and author for credibility and bias',
        explanation: 'Understanding where the information comes from is a fundamental step in evaluating its reliability.',
      },
      {
        id: 'ct8',
        question: 'What is the difference between a fact and an opinion?',
        options: ['A fact is true, an opinion is false', 'A fact can be proven, an opinion is a belief or judgment', 'Facts are long, opinions are short', 'There is no difference'],
        answer: 'A fact can be proven, an opinion is a belief or judgment',
        explanation: 'Facts are objective and verifiable, while opinions are subjective and not provable.',
      },
      {
        id: 'ct9',
        question: 'You are presented with a graph showing a dramatic increase. What should you check on the Y-axis first?',
        options: ['The color of the line', 'The font size', 'The scale and starting point', 'The title of the graph'],
        answer: 'The scale and starting point',
        explanation: 'The scale of the Y-axis can be manipulated to make changes look more or less dramatic than they are (e.g., not starting at zero).',
      },
      {
        id: 'ct10',
        question: 'What is confirmation bias?',
        options: ['The tendency to confirm your appointments', 'The tendency to search for, interpret, and recall information that confirms one\'s preexisting beliefs', 'A bias against new information', 'A type of statistical error'],
        answer: 'The tendency to search for, interpret, and recall information that confirms one\'s preexisting beliefs',
        explanation: 'Confirmation bias is a common cognitive bias that can affect objective reasoning.',
      },
    ],
  },
  {
    id: 'attention-to-detail',
    name: 'Attention to Detail',
    description: 'Test your ability to spot small details and inconsistencies.',
    duration: 1,
    questions: [
      {
        id: 'ad1',
        question: 'Find the different character: OOOOQOOOO',
        options: ['First O', 'Fifth character', 'Last O', 'No difference'],
        answer: 'Fifth character',
        explanation: 'The fifth character in the sequence is a Q, not an O.',
      },
      {
        id: 'ad2',
        question: 'Count the number of \'f\'s (upper or lower case) in the following sentence: "Finished files are the result of years of scientific study combined with the experience of years."',
        options: ['3', '4', '5', '6'],
        answer: '6',
        explanation: 'There are 6 \'f\'s in the sentence. It\'s a classic test where people often miss the \'f\' in "of".',
      },
      {
        id: 'ad3',
        question: 'Which number is different in the following sequence: 88888888888B88888',
        options: ['The first 8', 'The last 8', 'The letter B', 'They are all the same'],
        answer: 'The letter B',
        explanation: 'The sequence contains a letter B disguised among the number 8s.',
      },
      {
        id: 'ad4',
        question: 'Transcribe the following code exactly: AzB-7xY-pQ2',
        options: ['AzB-7xY-pQ2', 'AzB-7XY-pQ2', 'ABz-7xY-pQ2', 'AzB-7xY-PQ2'],
        answer: 'AzB-7xY-pQ2',
        explanation: 'This tests the ability to copy a sequence of characters with mixed case and numbers exactly.',
      },
      {
        id: 'ad5',
        question: 'Read the list: Apple, Banana, Orange, Peah, Grape. Which word is misspelled?',
        options: ['Apple', 'Banana', 'Orange', 'Peah'],
        answer: 'Peah',
        explanation: 'The word "Peah" is likely a misspelling of "Peach".',
      },
      {
        id: 'ad6',
        question: 'Are these two addresses identical? 1234 Maple Ave. and 1234 Maple Ave',
        options: ['Yes', 'No'],
        answer: 'No',
        explanation: 'The first address ends with a period after "Ave.", while the second one does not.',
      },
      {
        id: 'ad7',
        question: 'Follow the instruction: Click the fourth option.',
        options: ['Option 1', 'Option 2', 'Option 3', 'Option 4'],
        answer: 'Option 4',
        explanation: 'This is a simple test of following a direct instruction.',
      },
      {
        id: 'ad8',
        question: 'Find the pair that does not match: (A,a), (B,b), (C,d), (D,d)',
        options: ['(A,a)', '(B,b)', '(C,d)', '(D,d)'],
        answer: '(C,d)',
        explanation: 'The first three pairs should be the same letter in upper and lower case. (C,c) would be correct.',
      },
      {
        id: 'ad9',
        question: 'How many times does the number \'9\' appear in the integers from 1 to 100?',
        options: ['10', '19', '20', '21'],
        answer: '20',
        explanation: 'It appears in 9, 19, 29, 39, 49, 59, 69, 79, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99 (twice). That is 20 times.',
      },
      {
        id: 'ad10',
        question: 'Compare the two strings: "hello world" vs "helo world". Is there a difference?',
        options: ['Yes', 'No'],
        answer: 'Yes',
        explanation: 'The first string has two "l"s in "hello", while the second has only one.',
      },
    ],
  },
  {
    id: 'problem-solving',
    name: 'Problem Solving',
    description: 'Apply logical and creative thinking to solve complex problems.',
    duration: 1,
    questions: [
      {
        id: 'ps1',
        question: 'You have a 3-gallon jug and a 5-gallon jug. How can you measure exactly 4 gallons of water?',
        options: ['It is impossible', 'Fill the 3-gallon jug and pour it into the 5-gallon jug twice.', 'Fill the 5-gallon jug, pour into the 3-gallon jug. Empty the 3-gallon jug. Pour the remaining 2 gallons from the 5-gallon jug into the 3-gallon jug. Fill the 5-gallon jug and use it to top up the 3-gallon jug.', 'Fill the 3-gallon jug and pour it into the 5-gallon jug. Refill the 3-gallon jug and pour until the 5-gallon jug is full.'],
        answer: 'Fill the 5-gallon jug, pour into the 3-gallon jug. Empty the 3-gallon jug. Pour the remaining 2 gallons from the 5-gallon jug into the 3-gallon jug. Fill the 5-gallon jug and use it to top up the 3-gallon jug.',
        explanation: 'This is a classic water jug riddle. Following these steps precisely yields 4 gallons in the 5-gallon jug.',
      },
      {
        id: 'ps2',
        question: 'A bat and a ball cost $1.10 in total. The bat costs $1.00 more than the ball. How much does the ball cost?',
        options: ['$0.10', '$0.05', '$1.00', '$0.15'],
        answer: '$0.05',
        explanation: 'Let the ball cost x. Then the bat costs x + $1.00. x + (x + $1.00) = $1.10 => 2x = $0.10 => x = $0.05.',
      },
      {
        id: 'ps3',
        question: 'You are in a room with two doors and two guards. One guard always lies, one always tells the truth. One door leads to freedom, one to death. What one question do you ask a guard to find the door to freedom?',
        options: ['"Which door is the freedom door?"', '"Which door would the other guard say is the freedom door?"', '"Are you the truth-teller?"', '"Does that door lead to freedom?"'],
        answer: '"Which door would the other guard say is the freedom door?"',
        explanation: 'Asking this question to either guard will result in them pointing to the door of death. Therefore, you choose the other door.',
      },
      {
        id: 'ps4',
        question: 'A farmer has 17 sheep, and all but 9 die. How many are left?',
        options: ['17', '9', '8', '0'],
        answer: '9',
        explanation: 'This is a wordplay question. "All but 9 die" means that 9 sheep are the ones that did not die.',
      },
      {
        id: 'ps5',
        question: 'How can you divide a round cake into 8 equal pieces with only 3 straight cuts?',
        options: ['It is impossible', 'Cut it in half, then half again, then half again.', 'Cut an "X" on top, then cut it horizontally through the middle.', 'Stack the pieces after each cut.'],
        answer: 'Cut an "X" on top, then cut it horizontally through the middle.',
        explanation: 'Two cuts on top divide the cake into 4 pieces. A single horizontal cut through the middle then doubles the number of pieces to 8.',
      },
      {
        id: 'ps6',
        question: 'A man is looking at a portrait. Someone asks whose portrait it is. He replies, "Brothers and sisters I have none, but that man\'s father is my father\'s son." Who is in the portrait?',
        options: ['His father', 'His son', 'Himself', 'His uncle'],
        answer: 'His son',
        explanation: 'Since he has no brothers, "my father\'s son" can only be himself. So, the man in the portrait\'s father is the speaker. Therefore, the man in the portrait is his son.',
      },
      {
        id: 'ps7',
        question: 'What comes next in the sequence: J, F, M, A, M, J, J, __?',
        options: ['A', 'S', 'O', 'N'],
        answer: 'A',
        explanation: 'The letters are the first letter of the months of the year: January, February, March, April, May, June, July, August.',
      },
      {
        id: 'ps8',
        question: 'Rearrange the letters "O O U S W T D R E" to make one word.',
        options: ['OUTSWORDED', 'DOORWETSOUT', 'OUTDOORWETS', 'There is no such word'],
        answer: 'OUTSWORDED',
        explanation: 'This is an anagram puzzle. The letters spell OUTSWORDED.',
      },
      {
        id: 'ps9',
        question: 'You have two ropes that each take exactly 1 hour to burn from end to end. They don\'t burn at a uniform rate. How can you measure 45 minutes?',
        options: ['Light one rope at both ends.', 'Light one rope at one end.', 'Light one rope at both ends, and the second rope at one end simultaneously. When the first rope burns out (30 mins), light the other end of the second rope.', 'It is impossible.'],
        answer: 'Light one rope at both ends, and the second rope at one end simultaneously. When the first rope burns out (30 mins), light the other end of the second rope.',
        explanation: 'When the first rope burns out, 30 minutes have passed. At this moment, the second rope has 30 minutes of burn time left. By lighting its other end, it will now take 15 more minutes to burn completely. 30 + 15 = 45 minutes.',
      },
      {
        id: 'ps10',
        question: 'If you have a bowl with six apples and you take away four, how many do you have?',
        options: ['2', '4', '6', '10'],
        answer: '4',
        explanation: 'This is a riddle. If you "take away" four apples, you are the one who has them.',
      },
    ],
  },
  {
    id: 'creativity',
    name: 'Creativity',
    description: 'Test your ability to think outside the box and generate new ideas.',
    duration: 1,
    questions: [
      {
        id: 'cr1',
        question: 'How many uses can you think of for a brick?',
        options: ['Only for building', 'As a doorstop', 'As a paperweight', 'Dozens of uses, including building, a doorstop, a weapon, a step, a piece of art, etc.'],
        answer: 'Dozens of uses, including building, a doorstop, a weapon, a step, a piece of art, etc.',
        explanation: 'This question tests divergent thinking. A brick can be used for many purposes beyond its primary function.',
      },
      {
        id: 'cr2',
        question: 'What can you do with a paperclip besides holding papers together?',
        options: ['Only hold papers', 'Reset electronics, pick a lock, create a sculpture', 'Use as a bookmark', 'All of the above'],
        answer: 'All of the above',
        explanation: 'This tests the ability to see alternative uses for common objects.',
      },
      {
        id: 'cr3',
        question: 'Write a six-word story.',
        options: ['This is not a story.', 'Once upon a time, they lived.', 'For sale: baby shoes, never worn.', 'He went to the store to buy milk.'],
        answer: 'For sale: baby shoes, never worn.',
        explanation: 'This is a famous example of a six-word story that implies a much larger narrative, testing imagination and conciseness.',
      },
      {
        id: 'cr4',
        question: 'A new product is a "smart" water bottle. Which feature is most creative?',
        options: ['It holds water', 'It has a light that reminds you to drink', 'It tracks your sips and syncs with a health app', 'It purifies water using UV light and can also act as a bluetooth speaker'],
        answer: 'It purifies water using UV light and can also act as a bluetooth speaker',
        explanation: 'This option combines multiple, less obvious functions into a single product, showing more creative thinking.',
      },
      {
        id: 'cr5',
        question: 'Combine two different animals to create a new one. Which is the most creative combination?',
        options: ['Liger (Lion + Tiger)', 'Giraffephant (Giraffe + Elephant)', 'Dogcat (Dog + Cat)', 'Zebrafish (Zebra + Fish)'],
        answer: 'Giraffephant (Giraffe + Elephant)',
        explanation: 'While all are combinations, combining two very distinct large mammals with unique features like a long neck and a trunk shows more imagination.',
      },
      {
        id: 'cr6',
        question: 'You have a candle, a box of thumbtacks, and a book of matches. How can you attach the candle to a wall so that it doesn\'t drip on the floor? (The Duncker candle problem)',
        options: ['It\'s impossible', 'Melt the candle wax to the wall', 'Tack the candle directly to the wall', 'Empty the tack box, tack the box to the wall, and place the candle in the box'],
        answer: 'Empty the tack box, tack the box to the wall, and place the candle in the box',
        explanation: 'This is a classic test of overcoming "functional fixedness" by seeing the box as more than just a container for tacks.',
      },
      {
        id: 'cr7',
        question: 'What would happen if humans could suddenly fly (unaided)?',
        options: ['Nothing would change', 'The airline industry would collapse', 'Cities might be built vertically, and transportation would be revolutionized', 'It would be too dangerous'],
        answer: 'Cities might be built vertically, and transportation would be revolutionized',
        explanation: 'This answer shows deeper thinking about the second and third-order consequences of such a change.',
      },
      {
        id: 'cr8',
        question: 'Design a new type of chair. Which is the most innovative idea?',
        options: ['A chair with 4 legs and a back', 'A chair made of a new, stronger plastic', 'A chair that hovers using magnetism', 'A chair with a cup holder'],
        answer: 'A chair that hovers using magnetism',
        explanation: 'This idea fundamentally rethinks what a chair is and how it works, representing a higher level of innovation.',
      },
      {
        id: 'cr9',
        question: 'Give an alternative ending to the fairy tale "Cinderella".',
        options: ['She marries the prince', 'She decides she doesn\'t want to marry the prince and opens a shoe store instead', 'The step-sisters apologize and they all become friends', 'The glass slipper breaks'],
        answer: 'She decides she doesn\'t want to marry the prince and opens a shoe store instead',
        explanation: 'This ending subverts the traditional "happily ever after" trope and gives the protagonist more agency, showing creative thought.',
      },
      {
        id: 'cr10',
        question: 'You have to market a common object, like "air". How would you do it?',
        options: ['"Air: You need it to breathe"', '"Experience Artisan Air, bottled at the source from pristine mountain peaks"', '"It\'s just air"', '"Air, now with more oxygen"'],
        answer: '"Experience Artisan Air, bottled at the source from pristine mountain peaks"',
        explanation: 'This applies branding and luxury marketing concepts to a ubiquitous commodity, which is a creative approach.',
      },
    ],
  },
  {
    id: 'emotional-intelligence',
    name: 'Emotional Intelligence',
    description: 'Assess your ability to perceive, use, understand, and manage emotions.',
    duration: 1,
    questions: [
      {
        id: 'ei1',
        question: 'A team member is visibly upset after a meeting. What is the best first step?',
        options: ['Ignore them to give them space.', 'Tell them to cheer up.', 'Privately ask if they are okay and want to talk.', 'Report their behavior to HR.'],
        answer: 'Privately ask if they are okay and want to talk.',
        explanation: 'Showing empathy and offering support in a private, non-intrusive way is a key component of emotional intelligence.',
      },
      {
        id: 'ei2',
        question: 'Your boss gives you credit for work a colleague did. How do you respond?',
        options: ['Accept the credit quietly', 'Publicly announce it was your colleague\'s work', 'Privately clarify with your boss and suggest they credit the colleague', 'Complain to HR'],
        answer: 'Privately clarify with your boss and suggest they credit the colleague',
        explanation: 'This approach is professional, respectful to your boss, and ensures your colleague gets the recognition they deserve.',
      },
      {
        id: 'ei3',
        question: 'You receive an angry email from a client. What is the best way to reply?',
        options: ['Reply immediately with an angry tone', 'Ignore the email', 'Wait a day to calm down, then write a calm, professional email that acknowledges their frustration', 'Forward the email to your boss without replying'],
        answer: 'Wait a day to calm down, then write a calm, professional email that acknowledges their frustration',
        explanation: 'Responding emotionally can escalate the situation. A calm and empathetic response is more likely to resolve the issue.',
      },
      {
        id: 'ei4',
        question: 'A friend is telling you about a problem. What is the difference between empathizing and sympathizing?',
        options: ['There is no difference', 'Empathy is feeling sorry for them; sympathy is understanding their feelings', 'Sympathy is feeling sorry for them; empathy is understanding and sharing their feelings', 'Empathy is giving advice; sympathy is just listening'],
        answer: 'Sympathy is feeling sorry for them; empathy is understanding and sharing their feelings',
        explanation: 'Empathy involves putting yourself in someone else\'s shoes, while sympathy is more about acknowledging their hardship from an external perspective.',
      },
      {
        id: 'ei5',
        question: 'You feel overwhelmed with your workload. How do you communicate this to your manager?',
        options: ['Complain to colleagues', 'Struggle in silence', 'Schedule a meeting to discuss your workload and collaboratively prioritize tasks', 'Stop working on some tasks'],
        answer: 'Schedule a meeting to discuss your workload and collaboratively prioritize tasks',
        explanation: 'Proactively and professionally communicating your challenges allows for a constructive solution.',
      },
      {
        id: 'ei6',
        question: 'How can you tell if someone is not being genuine in their apology?',
        options: ['They make eye contact', 'They say "I\'m sorry"', 'They say "I\'m sorry you feel that way"', 'They offer to fix the mistake'],
        answer: 'They say "I\'m sorry you feel that way"',
        explanation: 'This is a non-apology that shifts blame to the other person\'s reaction rather than taking responsibility for the action.',
      },
      {
        id: 'ei7',
        question: 'You made a mistake that affected your team. What is the first thing you should do?',
        options: ['Hope no one notices', 'Blame someone else', 'Take ownership of the mistake and inform the team', 'Try to fix it in secret'],
        answer: 'Take ownership of the mistake and inform the team',
        explanation: 'Accountability is a key part of emotional intelligence and building trust within a team.',
      },
      {
        id: 'ei8',
        question: 'Which of the following is a non-verbal cue that indicates someone is actively listening?',
        options: ['Crossing their arms', 'Avoiding eye contact', 'Nodding and maintaining eye contact', 'Constantly checking their phone'],
        answer: 'Nodding and maintaining eye contact',
        explanation: 'These are positive body language signals that show engagement and attentiveness.',
      },
      {
        id: 'ei9',
        question: 'What is self-awareness in the context of Emotional Intelligence?',
        options: ['Being aware of others\' emotions', 'Being aware of your own emotions and how they affect your thoughts and behavior', 'Being good at tests', 'Being popular'],
        answer: 'Being aware of your own emotions and how they affect your thoughts and behavior',
        explanation: 'Self-awareness is the foundation of EI, involving understanding your own strengths, weaknesses, and emotional triggers.',
      },
      {
        id: 'ei10',
        question: 'How can you provide constructive feedback to a colleague without offending them?',
        options: ['Criticize them in a group meeting', 'Use the "sandwich method" (praise, criticism, praise)', 'Focus on the specific behavior, not the person, and explain its impact', 'Send an anonymous note'],
        answer: 'Focus on the specific behavior, not the person, and explain its impact',
        explanation: 'This method is direct, objective, and helps the person understand the consequences of their actions without feeling personally attacked.',
      },
    ],
  },
];
